from datetime import timedelta
import random

class ChestHandler:
    def __init__(self, item_data, event_handler, error_generator):
        """
        Initialize the ChestHandler with item data, an EventHandler instance, and an ErrorGenerator instance.
        """
        self.item_data = item_data
        self.event_handler = event_handler
        self.error_generator = error_generator

    def open_chest(self, account_state, chest_id, event_date, account_map_data, events, start_timestamp_fix, emit):
        """
        Open a chest, grant a random item, and generate related events with error injection.
    
        Args:
            account_state (dict): The player's current state.
            chest_id (str): The ID of the chest to open (e.g., "c_common").
            account_id (str): The account ID of the player.
            session_id (str): The session ID.
            event_date (datetime): The timestamp for the event.
            account_map_data (dict): Static metadata for the account.
            events (list): The list of events in the session.
    
        Returns:
            tuple: (chest_reward, terminate_session, generated_events)
                - chest_reward (dict or None): Details of the rewarded item, or None if no chest was opened.
                - terminate_session (bool): Whether the session should terminate.
                - generated_events (list): Only the events generated by this method.
        """
        if chest_id not in self.item_data["chests"]:
            raise ValueError(f"Invalid chest ID: {chest_id}")
        
        # Check if the player has this chest
#        if account_state["chests"].get(chest_id, 0) <= 0:
#            print("No chests to open")
#            return None, event_date  # No chests to open
    
        # Generate a random item using the chest's lambda function
        rewarded_item = self.item_data["chests"][chest_id]()
        _, item_type, _ = rewarded_item.split("_", 2)
        item_category_map = {"wp": "weapons", "hi": "held_items", "arm": "armor"}
        item_category = item_category_map.get(item_type)
    
        if not item_category:
            raise ValueError(f"Unexpected item type in chest reward: {item_type}")
    
        # Generate sink_item event
        sink_event = emit(
            event_type="resource",
            event_subtype="sink_item",
            event_date=event_date,
            item_category="chests",
            item_id=chest_id,
            item_amount=1,
            reason=f"{chest_id}_opened"
        )
        sink_event, terminate_session = self.error_generator.attempt_event_replacement(
            sink_event, account_map_data, events, start_timestamp_fix
        )
        if terminate_session:
            return True, event_date # Terminate session if error occurs
        if sink_event:
            events.append(sink_event)
            # Deduct one chest
            account_state["chests"][chest_id] -= 1
            if account_state["chests"][chest_id] == 0:
                del account_state["chests"][chest_id]
            event_date += timedelta(seconds=random.randint(1, 5))
    
        # Generate source_item event
        source_event = emit(
            event_type="resource",
            event_subtype="source_item",
            event_date=event_date + timedelta(seconds=1),
            item_category=item_category,
            item_id=rewarded_item,
            item_amount=1,
            reason=f"{chest_id}_opened"
        )
        source_event, terminate_session = self.error_generator.attempt_event_replacement(
            source_event, account_map_data, events, start_timestamp_fix
        )
        if terminate_session:
            return True, event_date # Terminate session if error occurs
        if source_event:
            events.append(source_event)
            # Add the rewarded item to the player's inventory
            account_state["equipment"][item_category][rewarded_item] = (
                account_state["equipment"][item_category].get(rewarded_item, 0) + 1
            )
            account_state["__gear_dirty__"] = True
            event_date += timedelta(seconds=random.randint(1, 5))
    
        return False, event_date

    def open_all_chests(self, account_state, event_date, account_map_data, events, start_timestamp_fix, emit):
        """
        Open all chests in the player's inventory until session termination or all chests are opened.
    
        Args:
            account_state (dict): The player's current state.
            account_id (str): The account ID of the player.
            session_id (str): The session ID.
            event_date (datetime): The timestamp for the event.
            account_map_data (dict): Static metadata for the account.
            events (list): The list of events in the session.
    
        Returns:
            tuple: (terminate_session, event_date)
        """
        # Extract available chests as a list (including counts)
        chest_types = list(account_state["chests"].keys())  # Store chest types separately
    
        for chest_id in chest_types:
            # Continue opening chests of this type while they exist
            while chest_id in account_state["chests"] and account_state["chests"][chest_id] > 0:
                event_date += timedelta(seconds=random.randint(1, 5))
                terminate_session, event_date = self.open_chest(
                    account_state=account_state,
                    chest_id=chest_id,
                    event_date=event_date,
                    account_map_data=account_map_data,
                    events=events,
                    start_timestamp_fix=start_timestamp_fix,
                    emit=emit
                )
                if terminate_session:
                    return True, event_date  # Immediately exit on session termination
    
        return False, event_date  # Return if all chests were opened without termination
    
    def add_chest_to_inventory(self, account_state, chest_id, amount=1):
        """
        Add chests to the player's inventory.

        Args:
            account_state (dict): The player's current state.
            chest_id (str): The ID of the chest to add (e.g., "c_common").
            amount (int): The number of chests to add.
        """
        if "chests" not in account_state:
            account_state["chests"] = {}

        account_state["chests"][chest_id] = account_state["chests"].get(chest_id, 0) + amount